// pages/addPackage/addPackage.js
Page({
  data:{
    packageTypes:[
      {
      name:"package1",
      value:"包裹type1",
    },
    {
      name:"package2",
      value:"包裹type2",
    },
    {
      name:"package3",
      value:"包裹type3"
    }],
  },
//选中项发生变化时
choiceChanged:function(e){
  console.log(e.detail.value);
}
})